version: '3'

services:
  app:
    image: chinaboard/brewing-service
    restart: unless-stopped
    ports:
      - 6636:6636
    depends_on:
      - database
    environment:
      OPENAI_TOKEN: sk-5Cpzm6j3lB8LxVqKG1UWs5FkN8HrSCF6x3WJq1ECsGmklx
      OPENAI_BASE_URL: https://ai.openai.net/v1
      BARK_NOTIFY_DOMAIN: https://notify.bark.com
      BARK_NOTIFY_TOKEN: vZgkHTPK3FLe5u4
      WHISPER_ENDPOINT: whisperX:9000
#      OPENAI_PROXY: http://proxy
#      DOCKER_HOST: tcp://dockerHost:2375
      SHARE_DOMAIN: https://share.com
      MONGODB_CONN: mongodb://database:27017
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - whisperX
      - database

  database:
    image: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
      - mongodbcfg:/data/configdb

  mongoku:
    image: huggingface/mongoku
    environment:
      MONGOKU_DEFAULT_HOST: mongodb://database:27017
    ports:
      - '3100:3100'
    links:
      - database

  whisperX:
    image: chinaboard/whisperx-service # https://github.com/chinaboard/whisperX-service
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    environment:
      - ASR_MODEL=large
    ports:
      - 9000:9000
    volumes:
      - cache-whisper:/root/.cache

  volumes:
    mongodb: {}
    mongodbcfg: {}
    cache-whisper: {}