name: Build

on:
  push:
    branches: [ master ]

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

env:
  SERVICE_IMAGE_NAME: chinaboard/brewing-service
  WORKER_IMAGE_NAME: chinaboard/brewing-worker

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Log into registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          username: chinaboard
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get sha short
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "service=$(echo "${{ github.event.head_commit.message }}" | grep -o "service")" >> "$GITHUB_ENV"
          echo "worker=$(echo "${{ github.event.head_commit.message }}" | grep -o "worker")" >> "$GITHUB_ENV"
      - name: Build and push service image
        if: ${{ env.serivce }} == "service"
        run: |
          docker build -t ${{ env.SERVICE_IMAGE_NAME }}:${{ env.sha_short }} -t ${{ env.SERVICE_IMAGE_NAME }} -f service.Dockerfile .
          docker push ${{ env.SERVICE_IMAGE_NAME }}:${{ env.sha_short }}
          docker push ${{ env.SERVICE_IMAGE_NAME }}
      - name: Build and push worker image
        if: ${{ env.worker }} == "worker"
        run: |
          docker build -t ${{ env.WORKER_IMAGE_NAME }}:${{ env.sha_short }} -t ${{ env.WORKER_IMAGE_NAME }} -f worker.Dockerfile .
          docker push ${{ env.WORKER_IMAGE_NAME }}:${{ env.sha_short }}
          docker push ${{ env.WORKER_IMAGE_NAME }}